name: Build and Push ECR

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: ${{ secrets.AWS_REGION }}
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - id: login-ecr
              uses: aws-actions/amazon-ecr-login@v3

            - name: Build
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

            - name: Tag
              run: |
                  docker tag \
                    ${{ secrets.ECR_REPOSITORY }}:latest \
                    ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

            - name: Push
              run: |
                  docker push \
                    ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

            - name: Atualizar Lambda
              run: |
                  aws lambda update-function-code \
                    --function-name lambda-tse \
                    --image-uri \
                    ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
